### ISSUE TITLE
Animations Not Working

### ISSUE THREAD

**Issue by LivesleyWA** [aurelia/animator-velocity#10]
I am following the instructions from http://gooy.github.io/aurelia-animator-velocity/#/ since I assume this is similar code (looks it to me).

I have registered the plugin

```
 .plugin("aurelia-animator-velocity");
```

I added _au-animatate_ and _anim-enter_ and _anim-leave_ to the first element below the _template_ element - example below

```
<template>
  <section class="au-animate" anim-enter="transition.slideRightBigIn;{duration:2000}" anim-leave="transition.slideRightBigOut;{duration:2000}">
```

Something is happening but it looks like, irrespective of what I try, only the default fadeIn and fadeOut animation is working and the options are largely ignored. The velocity pack is being loaded as far as I can see.

**Comment by michaelmalonenz** [comment]
you shouldn't be qualifying your transition as `transition.*`:
try this:

``` html
<section class="au-animate" anim-enter="slideRightBigIn;{duration:2000}" anim-leave="slideRightBigOut;{duration:2000}">
```

**Comment by LivesleyWA** [comment]
Thanks for the information but it didn't work. Is there a project I can look at with this working?

**Comment by dredzone** [comment]
any update on this? facing same issue anim-\* attributes values are ignored

**Comment by EisenbergEffect** [comment]
@Aaike Can you chime in here and assist with these community members getting the proper configuration in place please?

**Comment by farid-am** [comment]
I` have exactly the same problem as described by Livesley. 

`<section class="au-animate" anim-enter="slideUpIn;{duration:5000}" anim-leave="slideUpOut;{duration:5000}">`

By adding the "au-animate", I get the default "fadeIn", "fadeOut" but everything inside  anim-enter and  anim-leave is ignored.

**Comment by DarienFord** [comment]
Just adding my weight here; I'm trying the stagger and it's just not working.

`<div class="au-stagger" anim-enter="transition.flipXIn;{duration:500,easing:linear}">`

**Comment by ngocvantran** [comment]
If I understand correctly, staggering is not really supported directly by Aurelia animators. Entrance, leave notifications are only sent to animators on item basis, not a list of items, so it's not possible for the animators to perform staggering animations. All examples I've seen of staggering with Aurelia now have to be done via your own code.
