### ISSUE TITLE
Force-feeding is not possible inline (cannot insert arrays)

### ISSUE THREAD

**Issue by Tarpsvo** [aurelia/animator-velocity#14]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.17

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
`parseJSObject()` function does not handle inline arrays correctly.

`anim-enter="{ height: [200, 0], opacity: [1, 0] }"` will be split by commas (`,`) and the resulting array will be a complete mess (instead of the expected key-value pairs).

**Expected/desired behavior:**
Force-feeding should be possible inline.

**Comment by Tarpsvo** [comment]
Proposed change: use a regex split instead to avoid commas inside square braces.

`[,]+(?![^\[]+\])`

**Comment by zewa666** [comment]
@Tarpsvo can you create a PR for this?

**Comment by Tarpsvo** [comment]
Hey. It's done.

I tested it on my Aurelia app and it worked. I did not run the automated tests in this repository though. In theory, this should not have affected anything else. :)
