### ISSUE TITLE
Error when a list was hidden then displayed again before leaving animation completed

### ISSUE THREAD

**Issue by Alexey1** [aurelia/animator-velocity#21]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 8

* **Node Version:**
6.9.2

* **NPM Version:**
4.3.0

* **JSPM OR Webpack AND Version**
Aurelia CLI 0.30.1

* **Browser:**
Chrome 60

* **Language:**
TypeScript 2.4.2

**Current behavior:**

1. Create a project with au new.
2. Add aurelia-animator-velocity as described [here](https://github.com/aurelia/animator-velocity/issues/13#issuecomment-245799650).
3.  
main.ts
```
import { Aurelia } from 'aurelia-framework'
import environment from './environment';

export function configure(aurelia: Aurelia) {
  aurelia.use
    .standardConfiguration()
    .plugin('aurelia-animator-velocity', instance => {
      instance.enterAnimation.options.duration = 1000;
      instance.leaveAnimation.options.duration = 1000;
    })
    .feature('resources');

  if (environment.debug) {
    aurelia.use.developmentLogging();
  }

  if (environment.testing) {
    aurelia.use.plugin('aurelia-testing');
  }

  aurelia.start().then(() => aurelia.setRoot());
}
```

app.ts
```
export class App {
  private toggle = true;
  private items = [];

  constructor() {
    for (let i = 0; i < 5; i++) {
      this.items.push('item ' + i);
    }
  }
}
```

app.html
```
<template>
  <input type="checkbox"
    id="chk"
    checked.bind="toggle">
  <label for="chk">toggle</label>
  <div>
    <div class="au-animate"
      if.bind="toggle">
      <div repeat.for="item of items"
        class="au-animate">${item}</div>
    </div>
  </div>
</template>
```

4. au run, load page, see "toggle" checkbox and list of 5 items. Click "toggle" checkbox twice under one second. The list is not shown and error in browser console:

```
Uncaught TypeError: Cannot read property 'item' of null
    at vendor-bundle.js:24268
    at ArrayRepeatStrategy.instanceChanged (vendor-bundle.js:24322)
    at Repeat.itemsChanged (vendor-bundle.js:23983)
    at Repeat.bind (vendor-bundle.js:23948)
    at Controller.bind (vendor-bundle.js:22055)
    at View.bind (vendor-bundle.js:20059)
    at If._runValueChanged (vendor-bundle.js:23746)
    at If.valueChanged (vendor-bundle.js:23701)
    at BehaviorPropertyObserver.selfSubscriber (vendor-bundle.js:22299)
    at BehaviorPropertyObserver.call (vendor-bundle.js:22165)
    at BehaviorPropertyObserver.setValue (vendor-bundle.js:22145)
    at If.descriptor.set [as value] (vendor-bundle.js:22254)
    at Object.setValue (vendor-bundle.js:9552)
    at Binding.updateTarget (vendor-bundle.js:10793)
    at Binding.call (vendor-bundle.js:10808)
    at SetterObserver.callSubscribers (vendor-bundle.js:6303)
```

**Expected/desired behavior:**

No error. List is shown.

**Comment by zewa666** [comment]
@Alexey1 thanks for reporting the issue. It is actually not related to the animator but to the ArrayRepeatStrategy from inside the templating-resources repo. We'll get a fix in place

**Comment by Alexey1** [comment]
The following change fixes the issue for me:

repeat.js file

```
  unbind() {
    this.scope = null;
    this.items = null;
    this.matcherBinding = null;
    //replace this line
    //this.viewSlot.removeAll(true);
    //with this one
    this.viewSlot.removeAll(true, true);
    this._unsubscribeCollection();
  }
```
As far as I can tell this causes repeater to skip leaving animations for children. Otherwise the repeater gets problematic state if it is bound again when if.bind becomes true while leaving animations are still in progress. 
In the case I had, repeater DOM elements are already removed when unbind is invoked so it seems reasonable to skip animations at that point. But I can't be sure if there is no other case where it might be required, so input is needed from someone with better knowledge of the framework.

**Comment by jdanyow** [comment]
@Alexey1 that looks like a good fix (using `skipAnimation===true` during unbind).

https://github.com/aurelia/templating/blob/master/src/view-slot.js#L313

**Comment by jdanyow** [comment]
@zewa666 what do you think- see any problems with this?

**Comment by zewa666** [comment]
@alexey1 do your leave animations still work with the fix? Since this fix would only be targeting repeaters the only thing left I could see in danger are staggering leave animations. Could you give them a try and if everything works create a PR? But all in all @jdanyow I agree the fix looks good and simple.

**Comment by zewa666** [comment]
@alexey1 ping

**Comment by Alexey1** [comment]
Hi, leaving animations worked in my case but I didn't have a chance yet to check if staggering animations work. I'll look into this tomorrow.

**Comment by zewa666** [comment]
That sounds awesome. I have a good feeling that those shouldn't be a problem either if leaving anims work

**Comment by Alexey1** [comment]
I couldn't make staggering to be applied automatically with ```if.bind``` without the proposed change. I couldn't find a code example for this either. 
If staggering is invoked manually in view model with something like this ```this.animator.animate(elementsList, 'fadeIn', { stagger: 250, duration: 1000 });```, then the proposed change shouldn't affect that in any way.

**Comment by zewa666** [comment]
Ok perfect so if you can create a PR I'll check whether that affects the CSS animator and we can merge that. Thanks again for the great help figuring out what caused the issue

**Comment by Alexey1** [comment]
@zewa666 done
